# Generated by Django 5.2.14 on 2026-05-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('normalization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('negative_quantity', 'Negative Quantity'), ('quantity_threshold', 'Quantity Above Threshold'), ('invalid_airport_code', 'Invalid Airport Code'), ('unknown_unit', 'Unknown Unit'), ('missing_required_field', 'Missing Required Field'), ('invalid_date_range', 'Invalid Date Range'), ('duplicate_meter_period', 'Duplicate Meter + Period')], max_length=100)),
                ('source_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='warning', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_rules', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='normalization.normalizedrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_flags', to='core.organization')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='validation.validationrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='validation__organiz_fc4c32_idx'), models.Index(fields=['normalized_record', 'status'], name='validation__normali_4dde87_idx')],
            },
        ),
    ]
