# Generated by Django 5.2.14 on 2026-05-28 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_csv', 'SAP CSV'), ('utility_csv', 'Utility CSV'), ('travel_api', 'Travel API')], max_length=50)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=20)),
                ('site_code', models.CharField(blank=True, max_length=100)),
                ('material_doc', models.CharField(blank=True, max_length=100)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('billing_end', models.DateField(blank=True, null=True)),
                ('tariff', models.CharField(blank=True, max_length=100)),
                ('traveler', models.CharField(blank=True, max_length=255)),
                ('departure_airport', models.CharField(blank=True, max_length=10)),
                ('arrival_airport', models.CharField(blank=True, max_length=10)),
                ('cabin_class', models.CharField(blank=True, max_length=50)),
                ('hotel_nights', models.IntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('normalization_warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='core.organization')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'review_status'], name='normalizati_organiz_b51c24_idx'), models.Index(fields=['source_type', 'record_date'], name='normalizati_source__a9efee_idx'), models.Index(fields=['organization', 'source_type'], name='normalizati_organiz_9d96e2_idx')],
            },
        ),
    ]
